#!/usr/bin/env python3
"""
analyze_trades.py

Reads a trades CSV (generated by generate_trades.py) and computes:

(a) Weighted (by quantity) average price of each stock over the entire time series.
(b) Vector of 10-trade unweighted moving average of price per stock.
(c) Vector of 10-trade weighted moving average per stock.
(d) Single best buy-first/sell-later trade per stock (max profit).

Usage:
    python3 analyze_trades.py [trades_csv_path]

Default CSV path: trades_10M.csv
"""

import sys
import time
from typing import Any

import numpy as np
import pandas as pd


# ----------------------------------------------------------------------
# Query (a): weighted average price per stock
# ----------------------------------------------------------------------


def query_weighted_average(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each stock:
        weighted_avg_price = sum(price * quantity) / sum(quantity)
    """
    tmp = df.copy()
    tmp["pv"] = tmp["price"] * tmp["quantity"]

    grouped = tmp.groupby("stocksymbol").agg(
        total_pv=("pv", "sum"),
        total_q=("quantity", "sum"),
    )

    grouped["weighted_avg_price"] = grouped["total_pv"] / grouped["total_q"]
    return grouped[["weighted_avg_price"]]


# ----------------------------------------------------------------------
# Query (b): 10-trade unweighted moving average per stock
# ----------------------------------------------------------------------


def query_moving_avg_unweighted(df: pd.DataFrame, window: int = 10) -> pd.DataFrame:
    """
    For each stocksymbol, ordered by time, compute a rolling mean of 'price'
    with window=10, min_periods=1.

    Returns a DataFrame with:
        stocksymbol, time, price, ma_unweighted
    """
    tmp = df.sort_values(["stocksymbol", "time"]).copy()

    tmp["ma_unweighted"] = (
        tmp.groupby("stocksymbol")["price"]
        .rolling(window=window, min_periods=1)
        .mean()
        .reset_index(level=0, drop=True)
    )

    return tmp[["stocksymbol", "time", "price", "ma_unweighted"]]


# ----------------------------------------------------------------------
# Query (c): 10-trade weighted moving average per stock
# ----------------------------------------------------------------------


def query_moving_avg_weighted(df: pd.DataFrame, window: int = 10) -> pd.DataFrame:
    """
    For each stocksymbol, ordered by time, compute the rolling 10-trade
    weighted moving average of price, using quantity as the weight.

    Efficient implementation via cumulative sums:

        pv_i = price_i * quantity_i
        cum_pv = cumsum(pv_i) per stock
        cum_q  = cumsum(quantity_i) per stock

        For each row j, the window [j-window+1 .. j] weighted average is:

            (cum_pv[j] - cum_pv[j-window]) / (cum_q[j] - cum_q[j-window])
    """
    tmp = df.sort_values(["stocksymbol", "time"]).copy()

    tmp["pv"] = tmp["price"] * tmp["quantity"]

    tmp["cum_pv"] = tmp.groupby("stocksymbol")["pv"].cumsum()
    tmp["cum_q"] = tmp.groupby("stocksymbol")["quantity"].cumsum()

    tmp["cum_pv_lag"] = tmp.groupby("stocksymbol")["cum_pv"].shift(window, fill_value=0)
    tmp["cum_q_lag"] = tmp.groupby("stocksymbol")["cum_q"].shift(window, fill_value=0)

    num = tmp["cum_pv"] - tmp["cum_pv_lag"]
    den = tmp["cum_q"] - tmp["cum_q_lag"]

    tmp["ma_weighted"] = num / den

    return tmp[["stocksymbol", "time", "price", "quantity", "ma_weighted"]]


# ----------------------------------------------------------------------
# Query (d): best buy-first/sell-later trade per stock
# ----------------------------------------------------------------------


def best_trade_for_stock(group: pd.DataFrame) -> pd.Series:
    """
    Given trades for one stock (sorted by time), compute the single best
    buy-first/sell-later trade (max profit).

    Returns:
        max_profit, buy_time, sell_time, buy_price, sell_price
    """
    prices = group["price"].to_numpy()
    times = group["time"].to_numpy()

    min_price = prices[0]
    min_time = times[0]

    best_profit = 0
    best_buy_time = min_time
    best_sell_time = min_time
    best_buy_price = min_price
    best_sell_price = min_price

    for i in range(1, len(prices)):
        profit = prices[i] - min_price
        if profit > best_profit:
            best_profit = profit
            best_buy_time = min_time
            best_sell_time = times[i]
            best_buy_price = min_price
            best_sell_price = prices[i]

        if prices[i] < min_price:
            min_price = prices[i]
            min_time = times[i]

    return pd.Series(
        {
            "max_profit": float(best_profit),
            "buy_time": int(best_buy_time),
            "sell_time": int(best_sell_time),
            "buy_price": int(best_buy_price),
            "sell_price": int(best_sell_price),
        }
    )


def query_best_trades(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply best_trade_for_stock to each stocksymbol.
    """
    tmp = df.sort_values(["stocksymbol", "time"]).copy()

    result = tmp.groupby("stocksymbol").apply(best_trade_for_stock)
    result = result.reset_index()

    return result


def main():
    if len(sys.argv) > 1:
        csv_path = sys.argv[1]
    else:
        csv_path = "trades_10M.csv"

    print(f"Reading trades from {csv_path} ...")
    t0 = time.time()
    df = pd.read_csv(csv_path)

    # df["time"] = df["time"].astype(np.int64)
    # df["quantity"] = df["quantity"].astype(np.int64)
    # df["price"] = df["price"].astype(np.int64)

    t1 = time.time()
    print(f"Loaded DataFrame with shape {df.shape} in {t1 - t0:.2f} s")
    print(df.head())

    print("\n=== (a) Weighted average price per stock ===")
    t0 = time.time()
    weighted_avg = query_weighted_average(df)
    t1 = time.time()
    print(f"(a) done in {t1 - t0:.2f} s")
    print("Head:")
    print(weighted_avg.head())
    # weighted_avg.to_csv("weighted_avg_per_stock.csv")

    print("\n=== (b) 10-trade unweighted moving averages ===")
    t0 = time.time()
    ma_unweighted = query_moving_avg_unweighted(df, window=10)
    t1 = time.time()
    print(f"(b) done in {t1 - t0:.2f} s")
    print("Head:")
    print(ma_unweighted.head(10))
    # ma_unweighted.to_csv("ma_unweighted_10.csv", index=False)

    print("\n=== (c) 10-trade weighted moving averages ===")
    t0 = time.time()
    ma_weighted = query_moving_avg_weighted(df, window=10)
    t1 = time.time()
    print(f"(c) done in {t1 - t0:.2f} s")
    print("Head:")
    print(ma_weighted.head(10))
    # ma_weighted.to_csv("ma_weighted_10.csv", index=False)
    
    print("\n=== (d) Best buy-first/sell-later trade per stock ===")
    t0 = time.time()
    best_trades = query_best_trades(df)
    t1 = time.time()
    print(f"(d) done in {t1 - t0:.2f} s")
    print("Head:")
    print(best_trades.head())
    # best_trades.to_csv("best_trades_per_stock.csv", index=False)


if __name__ == "__main__":
    main()
